### ISSUE TITLE
Can't add messages to transactions

### ISSUE THREAD

**Issue by carlfairclough** [dmihal/maker-devcon-burner-wallet#13]
1) Send to an address
2) Add a message
3) Send

The screen hangs, while the following error is given to console:
![image](https://user-images.githubusercontent.com/4670881/65369918-31b07900-dc64-11e9-8a15-468c3e438a9b.png)

**Comment by dmihal** [comment]
I believe this only happens with ganache, doing it on a normal chain should be fine.
