### ISSUE TITLE
[Bug] - QR scanner does not appear in Chrome

### ISSUE THREAD

**Issue by as-dr** [dmihal/maker-devcon-burner-wallet#36]
## Bug
In iOS Chrome (76.0.3809) Tapping on the `Scanner` button opens up the scanner modal, but the iOS camera does not activate. The screen looks like this:

![photo4942797125180303393](https://user-images.githubusercontent.com/6787950/65911299-d5a3ce00-e3a2-11e9-842a-041a8535ef20.jpg)

Tapping around the text (i.e. just below it) appears to open a link that brings up a prompt to Take a Photo, access the Photo Library or Browse:

![photo4942797125180303396](https://user-images.githubusercontent.com/6787950/65911421-fe2bc800-e3a2-11e9-9831-1ab8bd791576.jpg)

## To Reproduce
1. Open https://devcon-staging.burnerfactory.com/ in iOS Chrome.
1. Tap on the `Scanner` button between `Send` and Receive` at the bottom of the screen
1. The Scanner modal should appear.
1. Observe that only a white box is present where the camera should appear.

## Hypothesis
This works on Safari, but it prompts me for camera access before activating the camera. Perhaps the issue is around permissions? However I will note that Chrome already had permission to use my camera, so I'm not 100% certain on this hypothesis.

**Comment by carlfairclough** [comment]
@as-dr iOS does not allow other browsers to access the camera. There's nothing we can do about this other than use file upload (to do) or encourage use of the native camera app
